import {
  mdiCheckboxMarkedCircleOutline,
  mdiMagnify,
  mdiMenuDown,
  mdiChevronUp,
  mdiChevronDown,
  mdiReply,
  mdiCircleOutline,
  mdiBlockHelper,
  mdiCloseCircle,
  mdiAlertOutline,
  mdiHelpCircleOutline,
  mdiEmoticonHappy,
  mdiEmoticonHappyOutline,
  mdiHeart,
  mdiHeartOutline,
  mdiHeartHalf,
  mdiBasketball,
  mdiLanguageHtml5,
  mdiNodejs,
  mdiCodeJson,
  mdiLanguageMarkdown,
  mdiFilePdfBox,
  mdiFileImage,
  mdiFileDocumentOutline,
  mdiFileExcel,
  mdiFolder,
  mdiFolderOpen,
  mdiCloseCircleOutline,
  mdiFolderNetwork,
  mdiHomeVariant,
  mdiFileOutline,
  mdiVideoOutline,
  mdiRocketLaunchOutline,
  mdiTextBoxOutline,
  mdiOpenInNew,
  mdiStarCircleOutline,
  mdiWidgetsOutline,
  mdiAccountGroupOutline,
  mdiShieldStarOutline,
  mdiGithub,
  mdiReddit,
  // New icons for ant-design replacements
  mdiMenuFold,
  mdiApps,
  mdiTranslate,
  mdiCog,
  mdiChevronRight,
  mdiCheckCircle,
  mdiGift,
  mdiMessage,
  mdiBell,
  mdiGlobe,
  mdiFileTree,
  mdiArrowRight,
  mdiEyeOff,
  mdiEye,
  mdiMenu,
  mdiMinus,
  mdiViewDashboard,
  mdiChartLine,
  mdiIdCard,
  mdiDownload,
  mdiLogout,
  mdiAccount,
  mdiHelpCircle,
  mdiLock,
  mdiComment,
  mdiList,
  mdiPencil,
  mdiAccountBox,
  mdiWallet,
  mdiBrush,
  mdiViewAgenda,
  mdiMonitor,
} from '@mdi/js';

export const icons = {
  checkboxMarkedCircleOutline: mdiCheckboxMarkedCircleOutline,
  magnify: mdiMagnify,
  menuDown: mdiMenuDown,
  chevronUp: mdiChevronUp,
  chevronDown: mdiChevronDown,
  reply: mdiReply,
  circleOutline: mdiCircleOutline,
  blockHelper: mdiBlockHelper,
  closeCircle: mdiCloseCircle,
  alertOutline: mdiAlertOutline,
  helpCircleOutline: mdiHelpCircleOutline,
  emoticonHappy: mdiEmoticonHappy,
  emoticonHappyOutline: mdiEmoticonHappyOutline,
  heart: mdiHeart,
  heartOutline: mdiHeartOutline,
  heartHalf: mdiHeartHalf,
  basketball: mdiBasketball,
  languagehtml5: mdiLanguageHtml5,
  nodejs: mdiNodejs,
  codejson: mdiCodeJson,
  languagemarkdown: mdiLanguageMarkdown,
  filepdf: mdiFilePdfBox,
  fileimage: mdiFileImage,
  filedocumentoutline: mdiFileDocumentOutline,
  filexcel: mdiFileExcel,
  folder: mdiFolder,
  folderopen: mdiFolderOpen,
  closecircleoutline: mdiCloseCircleOutline,
  foldernetwork: mdiFolderNetwork,
  homevariant: mdiHomeVariant,
  videoOutline: mdiVideoOutline,
  fileoutline: mdiFileOutline,
  rocketLaunchOutline: mdiRocketLaunchOutline,
  textBoxOutline: mdiTextBoxOutline,
  openInNew: mdiOpenInNew,
  starCircleOutline: mdiStarCircleOutline,
  widgetsOutline: mdiWidgetsOutline,
  accountGroupOutline: mdiAccountGroupOutline,
  shieldStarOutline: mdiShieldStarOutline,
  github: mdiGithub,
  reddit: mdiReddit,
  // Ant-design replacements
  menuFold: mdiMenuFold,
  apps: mdiApps,
  translate: mdiTranslate,
  cog: mdiCog,
  chevronRight: mdiChevronRight,
  checkCircle: mdiCheckCircle,
  gift: mdiGift,
  message: mdiMessage,
  bell: mdiBell,
  globe: mdiGlobe,
  fileTree: mdiFileTree,
  arrowRight: mdiArrowRight,
  eyeOff: mdiEyeOff,
  eye: mdiEye,
  menu: mdiMenu,
  minus: mdiMinus,
  viewDashboard: mdiViewDashboard,
  chartLine: mdiChartLine,
  idCard: mdiIdCard,
  download: mdiDownload,
  logout: mdiLogout,
  account: mdiAccount,
  helpCircle: mdiHelpCircle,
  lock: mdiLock,
  comment: mdiComment,
  list: mdiList,
  pencil: mdiPencil,
  accountBox: mdiAccountBox,
  wallet: mdiWallet,
  brush: mdiBrush,
  viewAgenda: mdiViewAgenda,
  desktopOutline: mdiMonitor,
};
